name: 1200_poker

services:
  poker:
    container_name: poker
    image: ghcr.io/squid1127/1200-poker:main
    pull_policy: always

    env_file:
      - .env
    networks:
      - main

networks:
  main:
    driver: bridge
